// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.0
// source: netns.proto

package netns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NetNSService_ProcessPod_FullMethodName = "/netns.NetNSService/ProcessPod"
)

// NetNSServiceClient is the client API for NetNSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetNSServiceClient interface {
	// Receives pod name and namespace
	ProcessPod(ctx context.Context, in *PodRequest, opts ...grpc.CallOption) (*PodResponse, error)
}

type netNSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetNSServiceClient(cc grpc.ClientConnInterface) NetNSServiceClient {
	return &netNSServiceClient{cc}
}

func (c *netNSServiceClient) ProcessPod(ctx context.Context, in *PodRequest, opts ...grpc.CallOption) (*PodResponse, error) {
	out := new(PodResponse)
	err := c.cc.Invoke(ctx, NetNSService_ProcessPod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetNSServiceServer is the server API for NetNSService service.
// All implementations must embed UnimplementedNetNSServiceServer
// for forward compatibility
type NetNSServiceServer interface {
	// Receives pod name and namespace
	ProcessPod(context.Context, *PodRequest) (*PodResponse, error)
	mustEmbedUnimplementedNetNSServiceServer()
}

// UnimplementedNetNSServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNetNSServiceServer struct {
}

func (UnimplementedNetNSServiceServer) ProcessPod(context.Context, *PodRequest) (*PodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessPod not implemented")
}
func (UnimplementedNetNSServiceServer) mustEmbedUnimplementedNetNSServiceServer() {}

// UnsafeNetNSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetNSServiceServer will
// result in compilation errors.
type UnsafeNetNSServiceServer interface {
	mustEmbedUnimplementedNetNSServiceServer()
}

func RegisterNetNSServiceServer(s grpc.ServiceRegistrar, srv NetNSServiceServer) {
	s.RegisterService(&NetNSService_ServiceDesc, srv)
}

func _NetNSService_ProcessPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetNSServiceServer).ProcessPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetNSService_ProcessPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetNSServiceServer).ProcessPod(ctx, req.(*PodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetNSService_ServiceDesc is the grpc.ServiceDesc for NetNSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetNSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netns.NetNSService",
	HandlerType: (*NetNSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPod",
			Handler:    _NetNSService_ProcessPod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netns.proto",
}
